# get_students( course_id ) returns 
students = [
    [
        {
            "id": 64577,
            "name": "Van Alger",
            "created_at": "2024-04-08T15:50:25-07:00",
            "sortable_name": "Alger, Van",
            "short_name": "Van Alger",
            "sis_user_id": "006350911",
            "integration_id": "vha8",
            "login_id": "006350911",
            "pronouns": "he/him/his",
        },
        {
            "id": 80369,
            "name": "Isabella Alley",
            "created_at": "2024-09-12T06:41:40-07:00",
            "sortable_name": "Alley, Isabella",
            "short_name": "Isabella Alley",
            "sis_user_id": "006412009",
            "integration_id": "ira62",
            "login_id": "006412009",
        },
        {
            "id": 61509,
            "name": "Oliver Ambrosich",
            "created_at": "2024-02-07T14:47:10-07:00",
            "sortable_name": "Ambrosich, Oliver",
            "short_name": "Oliver Ambrosich",
            "sis_user_id": "006346648",
            "integration_id": "ora28",
            "login_id": "006346648",
        },
        {
            "id": 64038,
            "name": "Cameron Anderson",
            "created_at": "2024-03-29T04:15:12-07:00",
            "sortable_name": "Anderson, Cameron",
            "short_name": "Cameron Anderson",
            "sis_user_id": "006389703",
            "integration_id": "cja548",
            "login_id": "006389703",
        },
        {
            "id": 67262,
            "name": "Christopher Anderson",
            "created_at": "2024-05-28T12:27:06-07:00",
            "sortable_name": "Anderson, Christopher",
            "short_name": "Christopher Anderson",
            "sis_user_id": "006405037",
            "integration_id": "cea338",
            "login_id": "006405037",
            "pronouns": "he/him/his",
        },
        {
            "id": 69888,
            "name": "Mario Armenta-Gonzalez",
            "created_at": "2024-05-29T17:13:54-07:00",
            "sortable_name": "Armenta-Gonzalez, Mario",
            "short_name": "Mario Armenta-Gonzalez",
            "sis_user_id": "006384111",
            "integration_id": "ma4528",
            "login_id": "006384111",
            "pronouns": "he/him/his",
        },
        {
            "id": 35932,
            "name": "Shawn Avery",
            "created_at": "2023-06-13T03:17:15-07:00",
            "sortable_name": "Avery, Shawn",
            "short_name": "Shawn Avery",
            "sis_user_id": "006296769",
            "integration_id": "sma738",
            "login_id": "006296769",
        },
        {
            "id": 43821,
            "name": "Adrian Begay",
            "created_at": "2023-08-11T03:17:38-07:00",
            "sortable_name": "Begay, Adrian",
            "short_name": "Adrian Begay",
            "sis_user_id": "005722921",
            "integration_id": "ab4466",
            "login_id": "005722921",
        },
        {
            "id": 69095,
            "name": "Joey Belin",
            "created_at": "2024-05-29T17:02:19-07:00",
            "sortable_name": "Belin, Joey",
            "short_name": "Joey Belin",
            "sis_user_id": "006332468",
            "integration_id": "jab2739",
            "login_id": "006332468",
            "pronouns": "he/him/his",
        },
        {
            "id": 27654,
            "name": "Sammi Bergman",
            "created_at": "2023-04-27T04:03:44-07:00",
            "sortable_name": "Bergman, Sammi",
            "short_name": "Sammi Bergman",
            "sis_user_id": "006300396",
            "integration_id": "srb734",
            "login_id": "006300396",
        },
        {
            "id": 64575,
            "name": "Austin Bolstad",
            "created_at": "2024-04-08T14:38:02-07:00",
            "sortable_name": "Bolstad, Austin",
            "short_name": "Austin Bolstad",
            "sis_user_id": "006335968",
            "integration_id": "apb335",
            "login_id": "006335968",
            "pronouns": "he/him/his",
        },
        {
            "id": 63041,
            "name": "Bella Broker",
            "created_at": "2024-03-08T07:56:00-07:00",
            "sortable_name": "Broker, Bella",
            "short_name": "Bella Broker",
            "sis_user_id": "006346194",
            "integration_id": "bjb629",
            "login_id": "006346194",
            "pronouns": "Prefer not to say",
        },
        {
            "id": 66847,
            "name": "Shey Burbank",
            "created_at": "2024-05-20T10:36:08-07:00",
            "sortable_name": "Burbank, Shey",
            "short_name": "Shey Burbank",
            "sis_user_id": "006356198",
            "integration_id": "sab956",
            "login_id": "006356198",
            "pronouns": "he/him/his",
        },
        {
            "id": 80481,
            "name": "Ronnie Butler",
            "created_at": "2024-09-14T18:06:20-07:00",
            "sortable_name": "Butler, Ronnie",
            "short_name": "Ronnie Butler",
            "sis_user_id": "006407311",
            "integration_id": "rtb235",
            "login_id": "006407311",
        },
        {
            "id": 49874,
            "name": "Bex Cabral",
            "created_at": "2023-09-12T09:24:32-07:00",
            "sortable_name": "Cabral, Bex",
            "short_name": "Bex Cabral",
            "sis_user_id": "006335695",
            "integration_id": "rlc469",
            "login_id": "006335695",
        },
        {
            "id": 69861,
            "name": "Mason Carlson",
            "created_at": "2024-05-29T17:13:45-07:00",
            "sortable_name": "Carlson, Mason",
            "short_name": "Mason Carlson",
            "sis_user_id": "006359089",
            "integration_id": "mcc522",
            "login_id": "006359089",
            "pronouns": "he/him/his",
        },
        {
            "id": 67481,
            "name": "Austin Carmack",
            "created_at": "2024-05-29T16:40:08-07:00",
            "sortable_name": "Carmack, Austin",
            "short_name": "Austin Carmack",
            "sis_user_id": "006337240",
            "integration_id": "ajc2288",
            "login_id": "006337240",
        },
        {
            "id": 64889,
            "name": "Gavin Carpenter",
            "created_at": "2024-04-16T04:11:19-07:00",
            "sortable_name": "Carpenter, Gavin",
            "short_name": "Gavin Carpenter",
            "sis_user_id": "006349214",
            "integration_id": "ghc29",
            "login_id": "006349214",
            "pronouns": "he/him/his",
        },
        {
            "id": 11838,
            "name": "Caleb Cenderelli",
            "created_at": "2023-03-16T01:21:18-07:00",
            "sortable_name": "Cenderelli, Caleb",
            "short_name": "Caleb Cenderelli",
            "sis_user_id": "006150971",
            "integration_id": "cbc283",
            "login_id": "006150971",
        },
        {
            "id": 71943,
            "name": "Jeremiah Chlarson",
            "created_at": "2024-06-05T04:12:23-07:00",
            "sortable_name": "Chlarson, Jeremiah",
            "short_name": "Jeremiah Chlarson",
            "sis_user_id": "006399593",
            "integration_id": "jlc2334",
            "login_id": "006399593",
            "pronouns": "he/him/his",
        },
        {
            "id": 63505,
            "name": "Joshua Clampitt",
            "created_at": "2024-03-19T16:26:52-07:00",
            "sortable_name": "Clampitt, Joshua",
            "short_name": "Joshua Clampitt",
            "sis_user_id": "006390259",
            "integration_id": "jcc725",
            "login_id": "006390259",
            "pronouns": "he/him/his",
        },
        {
            "id": 50686,
            "name": "Jay Clark",
            "created_at": "2023-09-25T10:09:44-07:00",
            "sortable_name": "Clark, Jay",
            "short_name": "Jay Clark",
            "sis_user_id": "006354819",
            "integration_id": "jwc336",
            "login_id": "006354819",
            "pronouns": "Prefer not to say",
        },
        {
            "id": 70837,
            "name": "Sayra Colorado Hernandez",
            "created_at": "2024-05-29T17:25:48-07:00",
            "sortable_name": "Colorado Hernandez, Sayra",
            "short_name": "Sayra Colorado Hernandez",
            "sis_user_id": "006355954",
            "integration_id": "sc3898",
            "login_id": "006355954",
            "pronouns": "she/her/hers",
        },
        {
            "id": 52175,
            "name": "Corbin Comber",
            "created_at": "2023-10-26T20:06:36-07:00",
            "sortable_name": "Comber, Corbin",
            "short_name": "Corbin Comber",
            "sis_user_id": "006336008",
            "integration_id": "cmc2477",
            "login_id": "006336008",
            "pronouns": "he/him/his",
        },
        {
            "id": 67743,
            "name": "Beatriz Cruz",
            "created_at": "2024-05-29T16:45:26-07:00",
            "sortable_name": "Cruz, Beatriz",
            "short_name": "Beatriz Cruz",
            "sis_user_id": "006373726",
            "integration_id": "bac637",
            "login_id": "006373726",
            "pronouns": "she/her/they/them",
        },
        {
            "id": 44211,
            "name": "Jacob Dennis",
            "created_at": "2023-08-15T03:17:37-07:00",
            "sortable_name": "Dennis, Jacob",
            "short_name": "Jacob Dennis",
            "sis_user_id": "006062567",
            "integration_id": "jad825",
            "login_id": "006062567",
        },
        {
            "id": 71673,
            "name": "Julian Diaz",
            "created_at": "2024-06-03T08:53:47-07:00",
            "sortable_name": "Diaz, Julian",
            "short_name": "Julian Diaz",
            "sis_user_id": "006394762",
            "integration_id": "jcd3",
            "login_id": "006394762",
        },
        {
            "id": 37174,
            "name": "Keeon Dixon",
            "created_at": "2023-06-23T03:17:18-07:00",
            "sortable_name": "Dixon, Keeon",
            "short_name": "Keeon Dixon",
            "sis_user_id": "006289091",
            "integration_id": "ked379",
            "login_id": "006289091",
            "pronouns": "he/him/his",
        },
        {
            "id": 69533,
            "name": "Jake Domabyl",
            "created_at": "2024-05-29T17:07:21-07:00",
            "sortable_name": "Domabyl, Jake",
            "short_name": "Jake Domabyl",
            "sis_user_id": "005704791",
            "integration_id": "jpd254",
            "login_id": "005704791",
            "pronouns": "he/him/his",
        },
        {
            "id": 54785,
            "name": "Victoria Dukart-Anderson",
            "created_at": "2023-12-19T03:23:46-07:00",
            "sortable_name": "Dukart-Anderson, Victoria",
            "short_name": "Victoria Dukart-Anderson",
            "sis_user_id": "006372883",
            "integration_id": "vd442",
            "login_id": "006372883",
        },
        {
            "id": 39332,
            "name": "Taylor Engle",
            "created_at": "2023-07-07T03:25:34-07:00",
            "sortable_name": "Engle, Taylor",
            "short_name": "Taylor Engle",
            "sis_user_id": "005806458",
            "integration_id": "tre59",
            "login_id": "005806458",
            "pronouns": "they/them/their",
        },
        {
            "id": 87341,
            "name": "Hector Espinoza",
            "created_at": "2024-11-27T03:31:17-07:00",
            "sortable_name": "Espinoza, Hector",
            "short_name": "Hector Espinoza",
            "sis_user_id": "006336788",
            "integration_id": "hae69",
            "login_id": "006336788",
            "pronouns": "he/him/his",
        },
        {
            "id": 59559,
            "name": "Bri Estadt",
            "created_at": "2024-01-17T20:59:58-07:00",
            "sortable_name": "Estadt, Bri",
            "short_name": "Bri Estadt",
            "sis_user_id": "006358515",
            "integration_id": "se824",
            "login_id": "006358515",
            "pronouns": "they/them/their",
        },
        {
            "id": 70568,
            "name": "Paul-Martin Fearon Hernandez",
            "created_at": "2024-05-29T17:22:52-07:00",
            "sortable_name": "Fearon Hernandez, Paul-Martin",
            "short_name": "Paul-Martin Fearon Hernandez",
            "sis_user_id": "006255853",
            "integration_id": "pf265",
            "login_id": "006255853",
        },
        {
            "id": 68111,
            "name": "Christopher Fischer",
            "created_at": "2024-05-29T16:49:28-07:00",
            "sortable_name": "Fischer, Christopher",
            "short_name": "Christopher Fischer",
            "sis_user_id": "006369413",
            "integration_id": "clf387",
            "login_id": "006369413",
            "pronouns": "he/him/his",
        },
        {
            "id": 71175,
            "name": "Zach Flora",
            "created_at": "2024-05-29T17:28:25-07:00",
            "sortable_name": "Flora, Zach",
            "short_name": "Zach Flora",
            "sis_user_id": "006336507",
            "integration_id": "zmf43",
            "login_id": "006336507",
            "pronouns": "he/him/his",
        },
        {
            "id": 67208,
            "name": "Jace Fryberger",
            "created_at": "2024-05-27T20:06:30-07:00",
            "sortable_name": "Fryberger, Jace",
            "short_name": "Jace Fryberger",
            "sis_user_id": "006331710",
            "integration_id": "jsf275",
            "login_id": "006331710",
            "pronouns": "he/him/his",
        },
        {
            "id": 69362,
            "name": "Jaydon Galbreath",
            "created_at": "2024-05-29T17:06:37-07:00",
            "sortable_name": "Galbreath, Jaydon",
            "short_name": "Jaydon Galbreath",
            "sis_user_id": "006363299",
            "integration_id": "jwg282",
            "login_id": "006363299",
            "pronouns": "they/them/their",
        },
        {
            "id": 77202,
            "name": "Mia Gallo",
            "created_at": "2024-08-21T18:45:41-07:00",
            "sortable_name": "Gallo, Mia",
            "short_name": "Mia Gallo",
            "sis_user_id": "005035601",
            "integration_id": "mmg333",
            "login_id": "005035601",
            "pronouns": "she/her/hers",
        },
        {
            "id": 65444,
            "name": "Xavier Garcia",
            "created_at": "2024-04-25T13:12:50-07:00",
            "sortable_name": "Garcia, Xavier",
            "short_name": "Xavier Garcia",
            "sis_user_id": "006373109",
            "integration_id": "xkg2",
            "login_id": "006373109",
            "pronouns": "he/him/his",
        },
        {
            "id": 30457,
            "name": "Ethan Gardner",
            "created_at": "2023-05-03T18:34:49-07:00",
            "sortable_name": "Gardner, Ethan",
            "short_name": "Ethan Gardner",
            "sis_user_id": "006272642",
            "integration_id": "emg529",
            "login_id": "006272642",
        },
        {
            "id": 63841,
            "name": "Joel Gilles",
            "created_at": "2024-03-25T16:25:11-07:00",
            "sortable_name": "Gilles, Joel",
            "short_name": "Joel Gilles",
            "sis_user_id": "006346502",
            "integration_id": "dlg396",
            "login_id": "006346502",
            "pronouns": "he/him/they/them",
        },
        {
            "id": 26785,
            "name": "Haylie Godoy",
            "created_at": "2023-04-21T04:02:57-07:00",
            "sortable_name": "Godoy, Haylie",
            "short_name": "Haylie Godoy",
            "sis_user_id": "006332571",
            "integration_id": "hjg222",
            "login_id": "006332571",
        },
        {
            "id": 80477,
            "name": "Brandon Gonzalez Arellano",
            "created_at": "2024-09-14T15:04:06-07:00",
            "sortable_name": "Gonzalez Arellano, Brandon",
            "short_name": "Brandon Gonzalez Arellano",
            "sis_user_id": "006376179",
            "integration_id": "brg273",
            "login_id": "006376179",
            "pronouns": "he/him/his",
        },
        {
            "id": 87346,
            "name": "J.J. Gonzalez",
            "created_at": "2024-11-27T03:31:27-07:00",
            "sortable_name": "Gonzalez, J.J.",
            "short_name": "J.J. Gonzalez",
            "sis_user_id": "002566290",
            "integration_id": "jjg233",
            "login_id": "002566290",
        },
        {
            "id": 70686,
            "name": "Stephen Gouer",
            "created_at": "2024-05-29T17:23:27-07:00",
            "sortable_name": "Gouer, Stephen",
            "short_name": "Stephen Gouer",
            "sis_user_id": "006352055",
            "integration_id": "sag663",
            "login_id": "006352055",
        },
        {
            "id": 87343,
            "name": "Eric Groves",
            "created_at": "2024-11-27T03:31:21-07:00",
            "sortable_name": "Groves, Eric",
            "short_name": "Eric Groves",
            "sis_user_id": "006404327",
            "integration_id": "eeg276",
            "login_id": "006404327",
            "pronouns": "he/him/his",
        },
        {
            "id": 72424,
            "name": "Lareine Han",
            "created_at": "2024-06-18T04:25:12-07:00",
            "sortable_name": "Han, Lareine",
            "short_name": "Lareine Han",
            "sis_user_id": "006399849",
            "integration_id": "sh3265",
            "login_id": "006399849",
        },
        {
            "id": 80561,
            "name": "Shelton Hatfield",
            "created_at": "2024-09-17T00:02:13-07:00",
            "sortable_name": "Hatfield, Shelton",
            "short_name": "Shelton Hatfield",
            "sis_user_id": "006406342",
            "integration_id": "jsh463",
            "login_id": "006406342",
            "pronouns": "he/him/his",
        },
        {
            "id": 14519,
            "name": "Peter Hilbert",
            "created_at": "2023-03-16T01:24:10-07:00",
            "sortable_name": "Hilbert, Peter",
            "short_name": "Peter Hilbert",
            "sis_user_id": "006216990",
            "integration_id": "peh53",
            "login_id": "006216990",
            "pronouns": "he/him/his",
        },
        {
            "id": 14519,
            "name": "Peter Hilbert",
            "created_at": "2023-03-16T01:24:10-07:00",
            "sortable_name": "Hilbert, Peter",
            "short_name": "Peter Hilbert",
            "sis_user_id": "006216990",
            "integration_id": "peh53",
            "login_id": "006216990",
            "pronouns": "he/him/his",
        },
        {
            "id": 87344,
            "name": "Corin Hill",
            "created_at": "2024-11-27T03:31:24-07:00",
            "sortable_name": "Hill, Corin",
            "short_name": "Corin Hill",
            "sis_user_id": "006424132",
            "integration_id": "cdh445",
            "login_id": "006424132",
        },
        {
            "id": 69780,
            "name": "Lauren Howell",
            "created_at": "2024-05-29T17:12:02-07:00",
            "sortable_name": "Howell, Lauren",
            "short_name": "Lauren Howell",
            "sis_user_id": "006348489",
            "integration_id": "leh389",
            "login_id": "006348489",
            "pronouns": "she/her/hers",
        },
        {
            "id": 65177,
            "name": "Chia Yi Huang",
            "created_at": "2024-04-21T04:59:32-07:00",
            "sortable_name": "Huang, Chia Yi",
            "short_name": "Chia Yi Huang",
            "sis_user_id": "006394645",
            "integration_id": "ch2929",
            "login_id": "006394645",
        },
        {
            "id": 63301,
            "name": "Corey Ingram",
            "created_at": "2024-03-14T17:57:26-07:00",
            "sortable_name": "Ingram, Corey",
            "short_name": "Corey Ingram",
            "sis_user_id": "006354947",
            "integration_id": "cji48",
            "login_id": "006354947",
            "pronouns": "he/him/his",
        },
        {
            "id": 54846,
            "name": "Hasmieu Jalloh",
            "created_at": "2023-12-19T19:21:54-07:00",
            "sortable_name": "Jalloh, Hasmieu",
            "short_name": "Hasmieu Jalloh",
            "sis_user_id": "006336428",
            "integration_id": "hj377",
            "login_id": "006336428",
            "pronouns": "he/him/his",
        },
        {
            "id": 88387,
            "name": "Tavin Jane",
            "created_at": "2024-12-21T15:13:30-07:00",
            "sortable_name": "Jane, Tavin",
            "short_name": "Tavin Jane",
            "sis_user_id": "006431294",
            "integration_id": "tlj282",
            "login_id": "006431294",
        },
        {
            "id": 84430,
            "name": "Matthew Kettunen",
            "created_at": "2024-10-07T14:13:38-07:00",
            "sortable_name": "Kettunen, Matthew",
            "short_name": "Matthew Kettunen",
            "sis_user_id": "006354145",
            "integration_id": "mjk475",
            "login_id": "006354145",
            "pronouns": "he/him/his",
        },
        {
            "id": 36353,
            "name": "Somei Kundu",
            "created_at": "2023-06-14T03:16:58-07:00",
            "sortable_name": "Kundu, Somei",
            "short_name": "Somei Kundu",
            "sis_user_id": "006271318",
            "integration_id": "sk2762",
            "login_id": "006271318",
            "pronouns": "they/them/their",
        },
        {
            "id": 69013,
            "name": "Alex Lange",
            "created_at": "2024-05-29T17:02:01-07:00",
            "sortable_name": "Lange, Alex",
            "short_name": "Alex Lange",
            "sis_user_id": "006345989",
            "integration_id": "hal238",
            "login_id": "006345989",
            "pronouns": "she/her/hers",
        },
        {
            "id": 64517,
            "name": "Cam Larson",
            "created_at": "2024-04-06T11:16:08-07:00",
            "sortable_name": "Larson, Cam",
            "short_name": "Cam Larson",
            "sis_user_id": "005295102",
            "integration_id": "cnl97",
            "login_id": "005295102",
            "pronouns": "he/him/his",
        },
        {
            "id": 69197,
            "name": "Jake Lawton",
            "created_at": "2024-05-29T17:02:40-07:00",
            "sortable_name": "Lawton, Jake",
            "short_name": "Jake Lawton",
            "sis_user_id": "006360989",
            "integration_id": "jdl582",
            "login_id": "006360989",
            "pronouns": "he/him/his",
        },
        {
            "id": 64129,
            "name": "Christopher Leckey",
            "created_at": "2024-04-01T16:51:46-07:00",
            "sortable_name": "Leckey, Christopher",
            "short_name": "Christopher Leckey",
            "sis_user_id": "006393799",
            "integration_id": "csl285",
            "login_id": "006393799",
            "pronouns": "he/him/his",
        },
        {
            "id": 87290,
            "name": "Rockwell Leikness",
            "created_at": "2024-11-27T03:30:03-07:00",
            "sortable_name": "Leikness, Rockwell",
            "short_name": "Rockwell Leikness",
            "sis_user_id": "006432800",
            "integration_id": "rkl92",
            "login_id": "006432800",
        },
        {
            "id": 23596,
            "name": "Cody Lowery",
            "created_at": "2023-04-07T04:01:36-07:00",
            "sortable_name": "Lowery, Cody",
            "short_name": "Cody Lowery",
            "sis_user_id": "006287039",
            "integration_id": "cll449",
            "login_id": "006287039",
            "pronouns": "he/him/his",
        },
        {
            "id": 68591,
            "name": "Dylan Macdonald",
            "created_at": "2024-05-29T16:55:19-07:00",
            "sortable_name": "Macdonald, Dylan",
            "short_name": "Dylan Macdonald",
            "sis_user_id": "005287034",
            "integration_id": "ddm248",
            "login_id": "005287034",
        },
        {
            "id": 56778,
            "name": "Connor Mangus",
            "created_at": "2024-01-03T11:14:32-07:00",
            "sortable_name": "Mangus, Connor",
            "short_name": "Connor Mangus",
            "sis_user_id": "006373975",
            "integration_id": "cem677",
            "login_id": "006373975",
            "pronouns": "he/him/his",
        },
        {
            "id": 67931,
            "name": "Angeles Martinez",
            "created_at": "2024-05-29T16:46:08-07:00",
            "sortable_name": "Martinez, Angeles",
            "short_name": "Angeles Martinez",
            "sis_user_id": "006367004",
            "integration_id": "amm3784",
            "login_id": "006367004",
            "pronouns": "she/her/hers",
        },
        {
            "id": 68651,
            "name": "Eli Martinez",
            "created_at": "2024-05-29T16:57:55-07:00",
            "sortable_name": "Martinez, Eli",
            "short_name": "Eli Martinez",
            "sis_user_id": "006337503",
            "integration_id": "erm494",
            "login_id": "006337503",
            "pronouns": "he/him/his",
        },
        {
            "id": 87288,
            "name": "Evan Martinez",
            "created_at": "2024-11-27T03:30:00-07:00",
            "sortable_name": "Martinez, Evan",
            "short_name": "Evan Martinez",
            "sis_user_id": "006234620",
            "integration_id": "efm64",
            "login_id": "006234620",
        },
        {
            "id": 61467,
            "name": "Connor May",
            "created_at": "2024-02-07T14:47:06-07:00",
            "sortable_name": "May, Connor",
            "short_name": "Connor May",
            "sis_user_id": "006341239",
            "integration_id": "cgm278",
            "login_id": "006341239",
            "pronouns": "he/him/his",
        },
        {
            "id": 63713,
            "name": "Michael McArdle",
            "created_at": "2024-03-24T04:12:07-07:00",
            "sortable_name": "McArdle, Michael",
            "short_name": "Michael McArdle",
            "sis_user_id": "006368365",
            "integration_id": "mjm2432",
            "login_id": "006368365",
            "pronouns": "he/him/his",
        },
        {
            "id": 64934,
            "name": "Brett McMillan",
            "created_at": "2024-04-16T18:07:55-07:00",
            "sortable_name": "McMillan, Brett",
            "short_name": "Brett McMillan",
            "sis_user_id": "006346556",
            "integration_id": "brm427",
            "login_id": "006346556",
            "pronouns": "he/him/his",
        },
        {
            "id": 68794,
            "name": "Ethan Meacham",
            "created_at": "2024-05-29T16:58:23-07:00",
            "sortable_name": "Meacham, Ethan",
            "short_name": "Ethan Meacham",
            "sis_user_id": "006334350",
            "integration_id": "evm68",
            "login_id": "006334350",
            "pronouns": "he/him/his",
        },
        {
            "id": 61338,
            "name": "Liam Milinazzo",
            "created_at": "2024-02-07T14:46:55-07:00",
            "sortable_name": "Milinazzo, Liam",
            "short_name": "Liam Milinazzo",
            "sis_user_id": "006346749",
            "integration_id": "ljm454",
            "login_id": "006346749",
            "pronouns": "he/him/his",
        },
        {
            "id": 69616,
            "name": "Kylend Mitchell",
            "created_at": "2024-05-29T17:11:28-07:00",
            "sortable_name": "Mitchell, Kylend",
            "short_name": "Kylend Mitchell",
            "sis_user_id": "006351418",
            "integration_id": "kmm2624",
            "login_id": "006351418",
            "pronouns": "he/him/his",
        },
        {
            "id": 11046,
            "name": "Lucienne Morton",
            "created_at": "2023-03-16T01:20:32-07:00",
            "sortable_name": "Morton, Lucienne",
            "short_name": "Lucienne Morton",
            "sis_user_id": "006211350",
            "integration_id": "lsm262",
            "login_id": "006211350",
            "pronouns": "she/her/hers",
        },
        {
            "id": 77485,
            "name": "Diane Mumararungu",
            "created_at": "2024-08-23T04:38:19-07:00",
            "sortable_name": "Mumararungu, Diane",
            "short_name": "Diane Mumararungu",
            "sis_user_id": "006406095",
            "integration_id": "md2854",
            "login_id": "006406095",
            "pronouns": "she/her/hers",
        },
        {
            "id": 55200,
            "name": "Sophie Murphy",
            "created_at": "2024-01-01T10:07:17-07:00",
            "sortable_name": "Murphy, Sophie",
            "short_name": "Sophie Murphy",
            "sis_user_id": "006335373",
            "integration_id": "sbm269",
            "login_id": "006335373",
        },
        {
            "id": 21843,
            "name": "Jaden Murray",
            "created_at": "2023-03-29T04:06:36-07:00",
            "sortable_name": "Murray, Jaden",
            "short_name": "Jaden Murray",
            "sis_user_id": "006210479",
            "integration_id": "jfm238",
            "login_id": "006210479",
        },
        {
            "id": 69141,
            "name": "Hunter Navarro",
            "created_at": "2024-05-29T17:02:28-07:00",
            "sortable_name": "Navarro, Hunter",
            "short_name": "Hunter Navarro",
            "sis_user_id": "006383211",
            "integration_id": "hdn34",
            "login_id": "006383211",
            "pronouns": "he/him/his",
        },
        {
            "id": 87684,
            "name": "Andrew Noorda",
            "created_at": "2024-12-04T15:38:16-07:00",
            "sortable_name": "Noorda, Andrew",
            "short_name": "Andrew Noorda",
            "sis_user_id": "006421863",
            "integration_id": "ajn397",
            "login_id": "006421863",
            "pronouns": "he/him/his",
        },
        {
            "id": 65121,
            "name": "Jackson Oesterle",
            "created_at": "2024-04-19T11:20:38-07:00",
            "sortable_name": "Oesterle, Jackson",
            "short_name": "Jackson Oesterle",
            "sis_user_id": "006381812",
            "integration_id": "jmo439",
            "login_id": "006381812",
            "pronouns": "he/him/his",
        },
        {
            "id": 61236,
            "name": "Rose Ory",
            "created_at": "2024-02-07T14:46:48-07:00",
            "sortable_name": "Ory, Rose",
            "short_name": "Rose Ory",
            "sis_user_id": "006350180",
            "integration_id": "rbo9",
            "login_id": "006350180",
            "pronouns": "she/her/hers",
        },
        {
            "id": 65544,
            "name": "Jaziah Peralta",
            "created_at": "2024-04-28T15:35:28-07:00",
            "sortable_name": "Peralta, Jaziah",
            "short_name": "Jaziah Peralta",
            "sis_user_id": "006358277",
            "integration_id": "jp3553",
            "login_id": "006358277",
            "pronouns": "he/him/his",
        },
        {
            "id": 69244,
            "name": "Ivan Perisic",
            "created_at": "2024-05-29T17:02:54-07:00",
            "sortable_name": "Perisic, Ivan",
            "short_name": "Ivan Perisic",
            "sis_user_id": "006393136",
            "integration_id": "ip356",
            "login_id": "006393136",
            "pronouns": "he/him/his",
        },
        {
            "id": 69717,
            "name": "Kylee Peshlakai",
            "created_at": "2024-05-29T17:11:50-07:00",
            "sortable_name": "Peshlakai, Kylee",
            "short_name": "Kylee Peshlakai",
            "sis_user_id": "006379133",
            "integration_id": "kdp284",
            "login_id": "006379133",
            "pronouns": "she/her/hers",
        },
        {
            "id": 67569,
            "name": "Amanda Peterson",
            "created_at": "2024-05-29T16:40:26-07:00",
            "sortable_name": "Peterson, Amanda",
            "short_name": "Amanda Peterson",
            "sis_user_id": "006349793",
            "integration_id": "agp332",
            "login_id": "006349793",
            "pronouns": "she/her/hers",
        },
        {
            "id": 75766,
            "name": "Tarquin Pursley",
            "created_at": "2024-08-06T12:42:02-07:00",
            "sortable_name": "Pursley, Tarquin",
            "short_name": "Tarquin Pursley",
            "sis_user_id": "006412228",
            "integration_id": "tp825",
            "login_id": "006412228",
        },
        {
            "id": 71146,
            "name": "Walter Ramirez III",
            "created_at": "2024-05-29T17:28:17-07:00",
            "sortable_name": "Ramirez III, Walter",
            "short_name": "Walter Ramirez III",
            "sis_user_id": "006354358",
            "integration_id": "wnr7",
            "login_id": "006354358",
            "pronouns": "he/him/his",
        },
        {
            "id": 70357,
            "name": "Marlete Ramos Garcia",
            "created_at": "2024-05-29T17:18:59-07:00",
            "sortable_name": "Ramos Garcia, Marlete",
            "short_name": "Marlete Ramos Garcia",
            "sis_user_id": "006354930",
            "integration_id": "mr3742",
            "login_id": "006354930",
            "pronouns": "she/her/hers",
        },
        {
            "id": 66665,
            "name": "Alana Rankin",
            "created_at": "2024-05-15T16:46:21-07:00",
            "sortable_name": "Rankin, Alana",
            "short_name": "Alana Rankin",
            "sis_user_id": "006382970",
            "integration_id": "ajr892",
            "login_id": "006382970",
            "pronouns": "they/them/their",
        },
        {
            "id": 71487,
            "name": "Malikye Reynolds",
            "created_at": "2024-05-31T04:39:35-07:00",
            "sortable_name": "Reynolds, Malikye",
            "short_name": "Malikye Reynolds",
            "sis_user_id": "006364986",
            "integration_id": "mar2387",
            "login_id": "006364986",
            "pronouns": "he/him/his",
        },
        {
            "id": 23662,
            "name": "Keenan Roberts",
            "created_at": "2023-04-07T04:02:51-07:00",
            "sortable_name": "Roberts, Keenan",
            "short_name": "Keenan Roberts",
            "sis_user_id": "006263333",
            "integration_id": "kir54",
            "login_id": "006263333",
            "pronouns": "he/him/his",
        },
        {
            "id": 68980,
            "name": "Hailey Rock",
            "created_at": "2024-05-29T17:01:55-07:00",
            "sortable_name": "Rock, Hailey",
            "short_name": "Hailey Rock",
            "sis_user_id": "006343859",
            "integration_id": "hlr229",
            "login_id": "006343859",
            "pronouns": "she/her/hers",
        },
        {
            "id": 86814,
            "name": "Daniel Rodriguez",
            "created_at": "2024-11-12T18:51:28-07:00",
            "sortable_name": "Rodriguez, Daniel",
            "short_name": "Daniel Rodriguez",
            "sis_user_id": "006373162",
            "integration_id": "dar565",
            "login_id": "006373162",
            "pronouns": "Prefer not to say",
        },
        {
            "id": 34930,
            "name": "Felix Romero Bastida",
            "created_at": "2023-06-05T10:10:10-07:00",
            "sortable_name": "Romero Bastida, Felix",
            "short_name": "Felix Romero Bastida",
            "sis_user_id": "006273723",
            "integration_id": "fab85",
            "login_id": "006273723",
            "pronouns": "he/him/his",
        },
        {
            "id": 70572,
            "name": "Pierce Rothmeyer",
            "created_at": "2024-05-29T17:22:53-07:00",
            "sortable_name": "Rothmeyer, Pierce",
            "short_name": "Pierce Rothmeyer",
            "sis_user_id": "006373165",
            "integration_id": "pgr45",
            "login_id": "006373165",
            "pronouns": "he/him/his",
        },
        {
            "id": 70770,
            "name": "Shaun Roughton",
            "created_at": "2024-05-29T17:25:36-07:00",
            "sortable_name": "Roughton, Shaun",
            "short_name": "Shaun Roughton",
            "sis_user_id": "006344673",
            "integration_id": "skr279",
            "login_id": "006344673",
            "pronouns": "he/him/his",
        },
        {
            "id": 61483,
            "name": "Jarrod Saffioti",
            "created_at": "2024-02-07T14:47:07-07:00",
            "sortable_name": "Saffioti, Jarrod",
            "short_name": "Jarrod Saffioti",
            "sis_user_id": "006310991",
            "integration_id": "jss599",
            "login_id": "006310991",
            "pronouns": "he/him/his",
        },
        {
            "id": 40710,
            "name": "Joey Seymour",
            "created_at": "2023-07-21T03:23:22-07:00",
            "sortable_name": "Seymour, Joey",
            "short_name": "Joey Seymour",
            "sis_user_id": "006291998",
            "integration_id": "jds899",
            "login_id": "006291998",
        },
        {
            "id": 66019,
            "name": "Rakshit Singh",
            "created_at": "2024-05-05T12:36:40-07:00",
            "sortable_name": "Singh, Rakshit",
            "short_name": "Rakshit Singh",
            "sis_user_id": "006384294",
            "integration_id": "rs3433",
            "login_id": "006384294",
            "pronouns": "he/him/his",
        },
        {
            "id": 68450,
            "name": "Dyllon Smith",
            "created_at": "2024-05-29T16:54:49-07:00",
            "sortable_name": "Smith, Dyllon",
            "short_name": "Dyllon Smith",
            "sis_user_id": "006358466",
            "integration_id": "drs544",
            "login_id": "006358466",
            "pronouns": "he/him/his",
        },
        {
            "id": 63583,
            "name": "Nick Smithson",
            "created_at": "2024-03-20T17:32:17-07:00",
            "sortable_name": "Smithson, Nick",
            "short_name": "Nick Smithson",
            "sis_user_id": "006299604",
            "integration_id": "ncs274",
            "login_id": "006299604",
        },
        {
            "id": 62912,
            "name": "Italia Springfield",
            "created_at": "2024-03-06T21:22:26-07:00",
            "sortable_name": "Springfield, Italia",
            "short_name": "Italia Springfield",
            "sis_user_id": "006335256",
            "integration_id": "izs22",
            "login_id": "006335256",
            "pronouns": "she/her/hers",
        },
        {
            "id": 67708,
            "name": "Alessandro Taranto",
            "created_at": "2024-05-29T16:40:57-07:00",
            "sortable_name": "Taranto, Alessandro",
            "short_name": "Alessandro Taranto",
            "sis_user_id": "006393769",
            "integration_id": "ajt592",
            "login_id": "006393769",
        },
        {
            "id": 68274,
            "name": "Brady Thom",
            "created_at": "2024-05-29T16:50:06-07:00",
            "sortable_name": "Thom, Brady",
            "short_name": "Brady Thom",
            "sis_user_id": "006381183",
            "integration_id": "bmt347",
            "login_id": "006381183",
            "pronouns": "he/him/his",
        },
        {
            "id": 70067,
            "name": "Maya Tolliver",
            "created_at": "2024-05-29T17:14:40-07:00",
            "sortable_name": "Tolliver, Maya",
            "short_name": "Maya Tolliver",
            "sis_user_id": "006338213",
            "integration_id": "mit59",
            "login_id": "006338213",
            "pronouns": "she/her/hers",
        },
        {
            "id": 71048,
            "name": "Spencer Uphold",
            "created_at": "2024-05-29T17:26:31-07:00",
            "sortable_name": "Uphold, Spencer",
            "short_name": "Spencer Uphold",
            "sis_user_id": "006370356",
            "integration_id": "sju33",
            "login_id": "006370356",
            "pronouns": "he/him/his",
        },
        {
            "id": 68959,
            "name": "Jaslen Valdez",
            "created_at": "2024-05-29T17:01:50-07:00",
            "sortable_name": "Valdez, Jaslen",
            "short_name": "Jaslen Valdez",
            "sis_user_id": "006364746",
            "integration_id": "jav572",
            "login_id": "006364746",
            "pronouns": "she/her/hers",
        },
        {
            "id": 71463,
            "name": "Cj Van De Sande",
            "created_at": "2024-05-31T04:39:05-07:00",
            "sortable_name": "Van De Sande, Cj",
            "short_name": "Cj Van De Sande",
            "sis_user_id": "006381202",
            "integration_id": "cjv267",
            "login_id": "006381202",
        },
        {
            "id": 35772,
            "name": "David Vazquez",
            "created_at": "2023-06-10T03:19:00-07:00",
            "sortable_name": "Vazquez, David",
            "short_name": "David Vazquez",
            "sis_user_id": "006268476",
            "integration_id": "dv593",
            "login_id": "006268476",
        },
        {
            "id": 67854,
            "name": "Adrian Villegas Ortiz",
            "created_at": "2024-05-29T16:45:50-07:00",
            "sortable_name": "Villegas Ortiz, Adrian",
            "short_name": "Adrian Villegas Ortiz",
            "sis_user_id": "006337251",
            "integration_id": "asv233",
            "login_id": "006337251",
            "pronouns": "he/him/his",
        },
        {
            "id": 65141,
            "name": "Josh Aaron Villyat",
            "created_at": "2024-04-19T19:00:48-07:00",
            "sortable_name": "Villyat, Josh Aaron",
            "short_name": "Josh Aaron Villyat",
            "sis_user_id": "006394277",
            "integration_id": "jv2478",
            "login_id": "006394277",
        },
        {
            "id": 37219,
            "name": "Koima Wari",
            "created_at": "2023-06-23T03:17:21-07:00",
            "sortable_name": "Wari, Koima",
            "short_name": "Koima Wari",
            "sis_user_id": "006303543",
            "integration_id": "krw485",
            "login_id": "006303543",
        },
        {
            "id": 70468,
            "name": "Harley Weiss",
            "created_at": "2024-05-29T17:19:31-07:00",
            "sortable_name": "Weiss, Harley",
            "short_name": "Harley Weiss",
            "sis_user_id": "006371861",
            "integration_id": "mw2538",
            "login_id": "006371861",
            "pronouns": "he/him/his",
        },
        {
            "id": 67545,
            "name": "Ashe West",
            "created_at": "2024-05-29T16:40:21-07:00",
            "sortable_name": "West, Ashe",
            "short_name": "Ashe West",
            "sis_user_id": "006351764",
            "integration_id": "aaw475",
            "login_id": "006351764",
            "pronouns": "she/her/hers",
        },
        {
            "id": 68666,
            "name": "Elijah Wilson",
            "created_at": "2024-05-29T16:57:58-07:00",
            "sortable_name": "Wilson, Elijah",
            "short_name": "Elijah Wilson",
            "sis_user_id": "006331723",
            "integration_id": "elw326",
            "login_id": "006331723",
            "pronouns": "he/him/his",
        },
        {
            "id": 60668,
            "name": "John Wolfchief",
            "created_at": "2024-01-30T11:27:27-07:00",
            "sortable_name": "Wolfchief, John",
            "short_name": "John Wolfchief",
            "sis_user_id": "006354865",
            "integration_id": "jww266",
            "login_id": "006354865",
        },
        {
            "id": 67925,
            "name": "Braydan Yapit",
            "created_at": "2024-05-29T16:46:06-07:00",
            "sortable_name": "Yapit, Braydan",
            "short_name": "Braydan Yapit",
            "sis_user_id": "006358549",
            "integration_id": "bdy25",
            "login_id": "006358549",
            "pronouns": "he/him/his",
        },
        {
            "id": 10721,
            "name": "Ryan Yazzie",
            "created_at": "2023-03-16T01:20:15-07:00",
            "sortable_name": "Yazzie, Ryan",
            "short_name": "Ryan Yazzie",
            "sis_user_id": "006051284",
            "integration_id": "rsy25",
            "login_id": "006051284",
        },
        {
            "id": 71464,
            "name": "Christopher Yoder",
            "created_at": "2024-05-31T04:39:06-07:00",
            "sortable_name": "Yoder, Christopher",
            "short_name": "Christopher Yoder",
            "sis_user_id": "006373013",
            "integration_id": "cly64",
            "login_id": "006373013",
            "pronouns": "he/him/his",
        },
    ]
]


# possibly outdated
my_courses = [
    {
        "id": 15480,
        "name": "Academic Integrity @NAU for Students",
        "account_id": 122,
        "uuid": "q6jLRgQbz7SqBl1rV98Ux2VJBenmWVX73taa9Nzq",
        "start_at": "2023-08-28T07:00:00Z",
        "grading_standard_id": None,
        "is_public": False,
        "created_at": "2023-08-17T18:46:50Z",
        "course_code": "Academic Integrity @NAU for Students",
        "default_view": "modules",
        "root_account_id": 1,
        "enrollment_term_id": 1,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": None,
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": False,
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_q6jLRgQbz7SqBl1rV98Ux2VJBenmWVX73taa9Nzq.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 29148,
        "name": "Combo CS-465 (1247-12640), CS-465, CS-565 sections (Fall 2024 M16)",
        "account_id": 211,
        "uuid": "wicJk0eFMmtKJRmypi38mEcA7g2N3Y2xWAGucFHV",
        "start_at": "2024-08-26T07:00:00Z",
        "grading_standard_id": None,
        "is_public": None,
        "created_at": "2024-07-16T10:46:09Z",
        "course_code": "Combined CS sections - (1247-12640) DISTRIBUTED SYSTEMS (Fall 2024 M16) 001",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 244,
        "license": None,
        "grade_passback_setting": None,
        "end_at": "2024-12-14T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": False,
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_wicJk0eFMmtKJRmypi38mEcA7g2N3Y2xWAGucFHV.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 31787,
        "name": "Combo STA-478 (1247-8545), STA-578, STA-478 sections (Fall 2024 M16)",
        "account_id": 191,
        "uuid": "RMzKQ6SNO2dgI5MF9llK4d0A0NF5Do42RMvxvoRR",
        "start_at": "2024-08-26T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2024-07-16T10:49:04Z",
        "course_code": "Combined STA sections - (1247-8545) STATISTICAL COMPUTING (Fall 2024 M16) 001",
        "default_view": "modules",
        "root_account_id": 1,
        "enrollment_term_id": 244,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-12-14T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": False,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_RMzKQ6SNO2dgI5MF9llK4d0A0NF5Do42RMvxvoRR.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 18253,
        "name": "CS-126L (1241-3684) COMPUTER SCIENCE I LAB (Spring 2024 M16) 001",
        "account_id": 211,
        "uuid": "8gQrZk0stpDa4ko6KfQYg5u5Jf4vAJZ97N0DiV3Q",
        "start_at": "2024-01-16T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2023-10-27T10:37:11Z",
        "course_code": "CS-126L - SEC001 - COMPUTER SCIENCE I LAB",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 110,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-05-11T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_8gQrZk0stpDa4ko6KfQYg5u5Jf4vAJZ97N0DiV3Q.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "sis_course_id": "1241-NAU00-CS-126L-SEC001-3684.NAU-PSSIS",
        "integration_id": None,
        "enrollments": [
            {
                "type": "ta",
                "role": "TaEnrollment",
                "role_id": 5,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 18258,
        "name": "CS-126L (1241-3685) COMPUTER SCIENCE I LAB (Spring 2024 M16) 002",
        "account_id": 211,
        "uuid": "FEqTSKdvZr6lizPBYs14NyCNS0gLsElbNPqVcBvO",
        "start_at": "2024-01-16T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2023-10-27T10:37:11Z",
        "course_code": "CS-126L - SEC002 - COMPUTER SCIENCE I LAB",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 110,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-05-11T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_FEqTSKdvZr6lizPBYs14NyCNS0gLsElbNPqVcBvO.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "sis_course_id": "1241-NAU00-CS-126L-SEC002-3685.NAU-PSSIS",
        "integration_id": None,
        "enrollments": [
            {
                "type": "ta",
                "role": "TaEnrollment",
                "role_id": 5,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 18266,
        "name": "CS-126L (1241-5043) COMPUTER SCIENCE I LAB (Spring 2024 M16) 004",
        "account_id": 211,
        "uuid": "pynoVepA5lCpuudt13m94SdfOD48qi2vuyZ4Sa4l",
        "start_at": "2024-01-16T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2023-10-27T10:37:11Z",
        "course_code": "CS-126L - SEC004 - COMPUTER SCIENCE I LAB",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 110,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-05-11T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_pynoVepA5lCpuudt13m94SdfOD48qi2vuyZ4Sa4l.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "sis_course_id": "1241-NAU00-CS-126L-SEC004-5043.NAU-PSSIS",
        "integration_id": None,
        "enrollments": [
            {
                "type": "ta",
                "role": "TaEnrollment",
                "role_id": 5,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 18271,
        "name": "CS-126L (1241-8161) COMPUTER SCIENCE I LAB (Spring 2024 M16) 005",
        "account_id": 211,
        "uuid": "ivfrkoi6j4scU0yVBP1cTUwwruJa8TyqdLkIJzqt",
        "start_at": "2024-01-16T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2023-10-27T10:37:11Z",
        "course_code": "CS-126L - SEC005 - COMPUTER SCIENCE I LAB",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 110,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-05-11T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_ivfrkoi6j4scU0yVBP1cTUwwruJa8TyqdLkIJzqt.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "sis_course_id": "1241-NAU00-CS-126L-SEC005-8161.NAU-PSSIS",
        "integration_id": None,
        "enrollments": [
            {
                "type": "ta",
                "role": "TaEnrollment",
                "role_id": 5,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 29096,
        "name": "CS-305 (1247-2607) COMPUTING TOOLS III (Fall 2024 M16) 001",
        "account_id": 211,
        "uuid": "44ktxqFbHE3qyqd7u7OzeThuAVZo1gZbAjik9DcD",
        "start_at": "2024-08-26T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2024-07-16T10:46:08Z",
        "course_code": "CS-305 - SEC001 - COMPUTING TOOLS III",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 244,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-12-14T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_44ktxqFbHE3qyqd7u7OzeThuAVZo1gZbAjik9DcD.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 32466,
        "name": "CS-345 (1247-5718) DATABASE SYSTEMS (Fall 2024 M16) 001",
        "account_id": 211,
        "uuid": "GssbrdSCB3frlJYQEn6P7OCv5f0CefHqVHAKmT95",
        "start_at": "2024-08-26T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2024-08-20T19:43:14Z",
        "course_code": "CS-345 - SEC001 - DATABASE SYSTEMS",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 244,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-12-14T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_GssbrdSCB3frlJYQEn6P7OCv5f0CefHqVHAKmT95.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 18398,
        "name": "CS-480 (1241-3810) OPERATING SYSTEMS (Spring 2024 M16) 001",
        "account_id": 211,
        "uuid": "VGPI03gm0k4rZfLV0d4pP6YvZOcty167kxGQH8IL",
        "start_at": "2024-01-12T07:00:00Z",
        "grading_standard_id": 14626,
        "is_public": False,
        "created_at": "2023-10-27T10:37:14Z",
        "course_code": "CS-480 - SEC001 - OPERATING SYSTEMS",
        "default_view": "modules",
        "root_account_id": 1,
        "enrollment_term_id": 110,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-05-11T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_VGPI03gm0k4rZfLV0d4pP6YvZOcty167kxGQH8IL.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "sis_course_id": "1241-NAU00-CS-480-SEC001-3810.NAU-PSSIS",
        "integration_id": None,
        "enrollments": [
            {
                "type": "ta",
                "role": "TaEnrollment",
                "role_id": 5,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 29888,
        "name": "CYB-310 (1247-2609) MALWARE ANALYSIS (Fall 2024 M16) 001",
        "account_id": 211,
        "uuid": "OLjGbLnx1jhKW5KJa2UuFvbRuvhrbEGauoKcpVQk",
        "start_at": "2024-08-26T07:00:00Z",
        "grading_standard_id": 234,
        "is_public": False,
        "created_at": "2024-07-16T10:46:23Z",
        "course_code": "CYB-310 - SEC001 - MALWARE ANALYSIS",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 244,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": "2024-12-14T06:59:59Z",
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "locale": "en",
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_OLjGbLnx1jhKW5KJa2UuFvbRuvhrbEGauoKcpVQk.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 23970,
        "name": "Information Security Awareness Training",
        "account_id": 121,
        "uuid": "opdPaUHWdDLQueej7NCrq47D2xoTiHqxGltmKx7R",
        "start_at": None,
        "grading_standard_id": None,
        "is_public": None,
        "created_at": "2024-03-08T17:06:43Z",
        "course_code": "Information Security Awareness Training",
        "default_view": "modules",
        "root_account_id": 1,
        "enrollment_term_id": 1,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": None,
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": True,
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_opdPaUHWdDLQueej7NCrq47D2xoTiHqxGltmKx7R.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": False,
    },
    {
        "id": 15608,
        "name": "Learning Online @ NAU",
        "account_id": 122,
        "uuid": "h4bvCeMoJwHTxY9dLDuR5XphoiorLtQGF3So5reE",
        "start_at": "2023-08-28T07:00:00Z",
        "grading_standard_id": None,
        "is_public": False,
        "created_at": "2023-08-23T23:34:44Z",
        "course_code": "Learning Online @ NAU",
        "default_view": "modules",
        "root_account_id": 1,
        "enrollment_term_id": 1,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": None,
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": False,
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_h4bvCeMoJwHTxY9dLDuR5XphoiorLtQGF3So5reE.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
    {
        "id": 1943,
        "name": "Passport to Canvas (Student Training)",
        "account_id": 120,
        "uuid": "QGRMgC93LMSGaWojdW25BufawZzePPnm981mnarS",
        "start_at": None,
        "grading_standard_id": None,
        "is_public": True,
        "created_at": "2022-11-18T16:36:01Z",
        "course_code": "Passport_to_Canvas",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 1,
        "license": "cc_by",
        "grade_passback_setting": None,
        "end_at": None,
        "public_syllabus": True,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": False,
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_QGRMgC93LMSGaWojdW25BufawZzePPnm981mnarS.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": False,
    },
    {
        "id": 15255,
        "name": "Teaching Online @ NAU",
        "account_id": 122,
        "uuid": "la16F1SFh1sOx34laLexfOwJFEjOjw8Xc9WVCCao",
        "start_at": "2023-08-21T07:00:00Z",
        "grading_standard_id": None,
        "is_public": False,
        "created_at": "2023-08-10T18:48:14Z",
        "course_code": "Teaching Online @ NAU",
        "default_view": "wiki",
        "root_account_id": 1,
        "enrollment_term_id": 1,
        "license": "private",
        "grade_passback_setting": None,
        "end_at": None,
        "public_syllabus": False,
        "public_syllabus_to_auth": False,
        "storage_quota_mb": 1048,
        "is_public_to_auth_users": False,
        "homeroom_course": False,
        "course_color": None,
        "friendly_name": None,
        "apply_assignment_group_weights": False,
        "calendar": {
            "ics": "https://canvas.nau.edu/feeds/calendars/course_la16F1SFh1sOx34laLexfOwJFEjOjw8Xc9WVCCao.ics"
        },
        "time_zone": "America/Phoenix",
        "blueprint": False,
        "template": False,
        "enrollments": [
            {
                "type": "student",
                "role": "StudentEnrollment",
                "role_id": 3,
                "user_id": 14604,
                "enrollment_state": "active",
                "limit_privileges_to_course_section": False,
            }
        ],
        "hide_final_grades": False,
        "workflow_state": "available",
        "restrict_enrollments_to_course_dates": True,
    },
]


student_dict = {
    "apb335": {"name": "Austin Bolstad", "course_id": 35791, "section": "004"},
    "sab956": {"name": "Shey Burbank", "course_id": 35791, "section": "004"},
    "ghc29": {"name": "Gavin Carpenter", "course_id": 35791, "section": "004"},
    "cbc283": {"name": "Caleb Cenderelli", "course_id": 35791, "section": "004"},
    "jwc336": {"name": "Jay Clark", "course_id": 35791, "section": "004"},
    "bac637": {"name": "Beatriz Cruz", "course_id": 35791, "section": "004"},
    "jad825": {"name": "Jacob Dennis", "course_id": 35791, "section": "004"},
    "tre59": {"name": "Taylor Engle", "course_id": 35791, "section": "004"},
    "hae69": {"name": "Hector Espinoza", "course_id": 35791, "section": "004"},
    "mmg333": {"name": "Mia Gallo", "course_id": 35791, "section": "004"},
    "brg273": {
        "name": "Brandon Gonzalez Arellano",
        "course_id": 35791,
        "section": "004",
    },
    "jjg233": {"name": "J.J. Gonzalez", "course_id": 35791, "section": "004"},
    "sh3265": {"name": "Lareine Han", "course_id": 35791, "section": "004"},
    "mjk475": {"name": "Matthew Kettunen", "course_id": 35791, "section": "004"},
    "sk2762": {"name": "Somei Kundu", "course_id": 35791, "section": "004"},
    "jdl582": {"name": "Jake Lawton", "course_id": 35791, "section": "004"},
    "ddm248": {"name": "Dylan Macdonald", "course_id": 35791, "section": "004"},
    "amm3784": {"name": "Angeles Martinez", "course_id": 35791, "section": "004"},
    "erm494": {"name": "Eli Martinez", "course_id": 35791, "section": "004"},
    "ljm454": {"name": "Liam Milinazzo", "course_id": 35791, "section": "004"},
    "lsm262": {"name": "Lucienne Morton", "course_id": 35791, "section": "004"},
    "sbm269": {"name": "Sophie Murphy", "course_id": 35791, "section": "004"},
    "ajn397": {"name": "Andrew Noorda", "course_id": 35791, "section": "004"},
    "rbo9": {"name": "Rose Ory", "course_id": 35791, "section": "004"},
    "jp3553": {"name": "Jaziah Peralta", "course_id": 35791, "section": "004"},
    "agp332": {"name": "Amanda Peterson", "course_id": 35791, "section": "004"},
    "ajr892": {"name": "Alana Rankin", "course_id": 35791, "section": "004"},
    "pgr45": {"name": "Pierce Rothmeyer", "course_id": 35791, "section": "004"},
    "izs22": {"name": "Italia Springfield", "course_id": 35791, "section": "004"},
    "bmt347": {"name": "Brady Thom", "course_id": 35791, "section": "004"},
    "mit59": {"name": "Maya Tolliver", "course_id": 35791, "section": "004"},
    "asv233": {"name": "Adrian Villegas Ortiz", "course_id": 35791, "section": "004"},
    "elw326": {"name": "Elijah Wilson", "course_id": 35791, "section": "004"},
    "jww266": {"name": "John Wolfchief", "course_id": 35791, "section": "004"},
}
